 version: 0.2 
  
 phases: 
   install: 
     runtime-versions: 
       java: corretto17
   pre_build: 
     commands: 
       - echo Nothing to do in this phase 
   build: 
     commands: 
       - echo Build started on `date` 
       - mvn clean package
   post_build: 
     commands: 
       - echo Nothing to do in this phase
 reports:
   junit:
     files:
      - '**/*'
     base-directory: "target/surefire-reports"
     file-format: 'JUnitXML'
 cache: 
   paths: 
     - '/root/.m2/**/*' 
