 version: 0.2 
  
 phases: 
   install: 
     runtime-versions: 
       java: corretto8 
   pre_build: 
     commands: 
       - echo Nothing to do in this phase 
       - chmod +x msedgedriver.exe
   build: 
     commands: 
       - echo Build started on `date` 
       - mvn clean package 
       - mvn test
   post_build: 
     commands: 
       - echo Nothing to do in this phase
 artifacts: 
   files: 
     - target/sampleproject.war
     - appspec.yml
     - deploy.sh
   discard-paths: yes 
 cache: 
   paths: 
     - '/root/.m2/**/*' 
